export const CLIENT_AUTH = 'CLIENT_AUTH';
export const CLIENT_AUTH_FULFILLED = 'CLIENT_AUTH_FULFILLED';
export const CLIENT_AUTH_REJECTED = 'CLIENT_AUTH_REJECTED';
export const CLIENT_AUTH_PENDING = 'CLIENT_AUTH_PENDING';
export const CLIENT_AUTH_EMPTY = 'CLIENT_AUTH_EMPTY';

export const ORDER_LIST_FULFILLED = "ORDER_LIST_FULFILLED"
export const ORDER_LIST_REJECTED = "ORDER_LIST_REJECTED"
export const ORDER_LIST_PENDING = "ORDER_LIST_PENDING"
export const ORDER_LIST_EMPTY = "ORDER_LIST_EMPTY"
export const ORDER_LIST = "ORDER_LIST"

export const CLIENT_LIST_FULFILLED = "CLIENT_LIST_FULFILLED"
export const CLIENT_LIST_REJECTED = "CLIENT_LIST_REJECTED"
export const CLIENT_LIST_PENDING = "CLIENT_LIST_PENDING"
export const CLIENT_LIST_EMPTY = "CLIENT_LIST_EMPTY"
export const CLIENT_LIST = "CLIENT_LIST"

export const SERVICE_INDUSTRIES_LIST_FULFILLED = "SERVICE_INDUSTRIES_LIST_FULFILLED"
export const SERVICE_INDUSTRIES_LIST_REJECTED = "SERVICE_INDUSTRIES_LIST_REJECTED"
export const SERVICE_INDUSTRIES_LIST_PENDING = "SERVICE_INDUSTRIES_LIST_PENDING"
export const SERVICE_INDUSTRIES_LIST_EMPTY = "SERVICE_INDUSTRIES_LIST_EMPTY"
export const SERVICE_INDUSTRIES_LIST = "SERVICE_INDUSTRIES_LIST"

export const SERVICE_CATEGORIES_LIST_FULFILLED = "SERVICE_CATEGORIES_LIST_FULFILLED"
export const SERVICE_CATEGORIES_LIST_REJECTED = "SERVICE_CATEGORIES_LIST_REJECTED"
export const SERVICE_CATEGORIES_LIST_PENDING = "SERVICE_CATEGORIES_LIST_PENDING"
export const SERVICE_CATEGORIES_LIST_EMPTY = "SERVICE_CATEGORIES_LIST_EMPTY"
export const SERVICE_CATEGORIES_LIST = "SERVICE_CATEGORIES_LIST"