export const CLIENT_AUTH = 'CLIENT_AUTH';
export const CLIENT_AUTH_FULFILLED = 'CLIENT_AUTH_FULFILLED';
export const CLIENT_AUTH_REJECTED = 'CLIENT_AUTH_REJECTED';
export const CLIENT_AUTH_PENDING = 'CLIENT_AUTH_PENDING';
export const CLIENT_AUTH_EMPTY = 'CLIENT_AUTH_EMPTY';

export const ORDER_LIST_FULFILLED = "ORDER_LIST_FULFILLED"
export const ORDER_LIST_REJECTED = "ORDER_LIST_REJECTED"
export const ORDER_LIST_PENDING = "ORDER_LIST_PENDING"
export const ORDER_LIST_EMPTY = "ORDER_LIST_EMPTY"
export const ORDER_LIST = "ORDER_LIST"